serverDev:
  host: "localhost"
  port: "8080"
serverProd:
  host: "0.0.0.0"
  port: "443"
certfile: "/etc/letsencrypt/live/api.bohdanabadi.com/fullchain.pem"
keyfile: "/etc/letsencrypt/live/api.bohdanabadi.com/privkey.pem"