name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 165.22.233.166 >> ~/.ssh/known_hosts    

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install Go on Server
        run: |
          sshpass ${{ secrets.SSH_PASSPHRASE }} ssh ${{ secrets.USERNAME }}@165.22.233.166 "sudo apt update && sudo apt install -y golang"

      - name: Build and Deploy
        run: |
          # Add your build and deployment commands here
          # Example: Assuming your project has a main.go file
          go build -o traffic-simulation
          scp traffic-simulation {{ secrets.USERNAME }}@165.22.233.166:${{ secrets.BACKEND_APP_DIRECTORY }}

          # Deploy
          sshpass ${{ secrets.SSH_PASSPHRASE }} ssh ${{ secrets.USERNAME }}@165.22.233.166 "cd ${{ secrets.BACKEND_APP_DIRECTORY }} && ./traffic-simulation"
